USE `utcdemo`;

INSERT INTO `address`(add_country, add_city)
VALUES (N'Sapa',               N'Lào Cai'),
       (N'Y tý ',              N'Lào Cai'),
       (N'Phố cổ Đồng Văn',    N'Hà Giang'),
       (N'Thị TRấn Mèo Vạc',   N'Hà Giang'),
       (N'Thác Dải Yếm',       N'Mộc Châu'),
       (N'Hạ Long',            N'Quảng Ninh'),
       (N'Bán Đảo Sơn Trà',    N'Đà Nẵng'),
       (N'Bãi biển Mỹ Khê',    N'Đà Nẵng'),
       (N'Tây Hồ',             N'Hà Nội'),
       (N'Lạng Sơn',           N'Lạng Sơn'),
       (N'Thái Bình',          N'Thái Bình'),
       (N'Hà Nam',             N'Phủ Lý'),
       (N'Quận 9',             N'TP HCM'),
       (N'Quận 2',             N'TP HCM'),
       (N'Long Biên',          N'Hà Nội'),
       (N'Tây Hồ',             N'Hà Nội');

INSERT INTO `guests`(g_first_name, g_last_name, g_idCard, g_credit_card, g_email,g_type,g_password, g_add_id,g_user_name)
VALUES (N'Hoàng',N'Việt','000012','0321654',N'hoangviet@gmail.com','GUESTS','$2a$12$DmJaRwd0cc51a3Gt7J1mxuDnVwEJUaCVZOKs3OVZm1bf2.bRZjl26',1,'hoangviet'),
       (N'Thanh',N'Ngân','02335', '3535323',N'thanhngan@gmail.com','GUESTS','$2a$12$DmJaRwd0cc51a3Gt7J1mxuDnVwEJUaCVZOKs3OVZm1bf2.bRZjl26',2,'thanhngan'),
       (N'Đỗ',N'Lượng','03216','658751',N'doluong@gmail.com','GUESTS','$2a$10$W2neF9.6Agi6kAKVq8q3fec5dHW8KUA.b0VSIGdIZyUravfLpyIFi',3,'doluong'),
       (N'TRần',N'Tuấn','89654', '6315726',N'trantuan@gmail.com','GUESTS','$2a$10$W2neF9.6Agi6kAKVq8q3fec5dHW8KUA.b0VSIGdIZyUravfLpyIFi',4,'trantuan'),
       (N'Ngọc',N'Như','64821', '635179',N'ngocnhu@gmail.com','GUESTS','$2a$10$W2neF9.6Agi6kAKVq8q3fec5dHW8KUA.b0VSIGdIZyUravfLpyIFi',5,'ngocnhu'),
       (N'Nguyễn',N'Nam','8943289', '465452',N'nguyennam@gmail.com','GUESTS','$2a$10$W2neF9.6Agi6kAKVq8q3fec5dHW8KUA.b0VSIGdIZyUravfLpyIFi',6,'nguyennam'),
       (N'Văn ',N'Định','68429', '987264',N'vandinh@gmail.com','GUESTS','$2a$10$W2neF9.6Agi6kAKVq8q3fec5dHW8KUA.b0VSIGdIZyUravfLpyIFi',7,'vandinh'),
       (N'Mạnh',N'Dương','97618', '5316487',N'manhduong@gmail.com','GUESTS','$2a$10$W2neF9.6Agi6kAKVq8q3fec5dHW8KUA.b0VSIGdIZyUravfLpyIFi',9,'manhduong'),
       (N'Nguyễn ',N'Duyệt','53184', '658463',N'tranluat@gmail.com','GUESTS','$2a$10$W2neF9.6Agi6kAKVq8q3fec5dHW8KUA.b0VSIGdIZyUravfLpyIFi',10,'theduyet'),
       (N'Xuân',N'Đức','897564', '5658975',N'xuanduc@gmail.com','GUESTS','$2a$10$W2neF9.6Agi6kAKVq8q3fec5dHW8KUA.b0VSIGdIZyUravfLpyIFi',8,'xuanduc');

INSERT INTO `hotel`(h_name, h_email_address, h_website, h_description, h_roomCount, h_addId)
VALUES (N'LuxuryHotel',                     N'hotel@gmail.com',                 N'lxury.vn',            N'Luxury là một trong những khách sạn ...',                                                     25,1),
       (N'Hoàng Kiều Homestay',             N'hoangkieu@gmail.com',             N'hoangkieu.com',       N'Hoàng kiều là một trong những homestay ...',                                                  20,2),
       (N'Hải Đăng',                        N'haidang@gmail.com',               N'haidang.vn',          N'Có vị trí đắc địa nhìn ra biển Hạ Long ...',                                                  20,6),
       (N'Sheraton',                        N'sheraton@gmail.com',              N'sheraton.vn',         N'Khách sạn Sheraton Hanoi đi vào hoạt động năm 2003....',                                      20,9),
       (N'Hotel De La Coupole',             N'delacoupole@gmail.com',           N'delacouple.com',      N'Hotel De La Coupole Sapa được tọa lạc tại một vị trí vô cùng đắc địa...',                     20,1),
       (N'InterContinental Hà Nội Westlake',N'intercontinental@gmail.com',      N'intercontinental.vn', N'Khách sạn InterContinental Hanoital Hanoi Westlake là sự  hàng tìm đến những giá trị...',     20,9),
       (N'Paos Sapa Leisure Hotel',         N'paoleisure@gmail.com',            N'paoleisure.vn',       N'Là khách sạn 5 sao đầu tiên của Sapa chỉ vừa mới được khai trương hồi tháng 9/ 2017, Pao’s ', 20,1),
       (N'Halong Paradise Suites',          N'halongparadies@gmail.com',        N'halongparadies.vn',   N'Khách sạn Halong Paradise Suites tọa lạc trên đảo Tuần Châu, thành phố ...',                  35,6),
       (N'Vinpearl Hotel Lạng Sơn',         N'vinpeallangson@gmail.com',        N'vinpearllangson.vn',  N'Tọa lạc tại trung tâm Thành phố Lạng Sơn với 21 tầng cao, Vinpearl Hotel .....',              20,10),
       ('Sub-Ex',                           'jlyddiard0@biblegateway.com',      'epa.gov',              'Balsamorhiza macrophylla Nutt.',                                                               25, 4),
        ('Tempsoft',                        'rcockroft1@liveinternet.ru',       'storify.com',          'Coryphantha robustispina (Schott ex Engelm.) Britton & Rose',                                  25, 3),
        ('Job',                             'lmcvicar2@dedecms.com',            'multiply.com',         'Elymus elymoides (Raf.) Swezey ssp. hordeoides (Suksd.) Barkworth',                            25, 4),
        ('Vagram',                          'jjosh3@acquirethisname.com',       'europa.eu',            'Ludwigia leptocarpa (Nutt.) H. Hara',                                                          25, 3),
        ('Tempsoft',                        'rmarson4@joomla.org',              'unblog.fr',            'Stachytarpheta mutabilis (Jacq.) Vahl',                                                        25, 3),
        ('Toughjoyfax',                     'dbathoe5@t.co',                    'illinois.edu',         'Pleurothallis R. Br.',                                                                         25, 3),
        ('Biodex',                          'kbarwell6@who.int',                'twitter.com',          'Aplodon wormskjoldii (Hornem.) Kindb.',                                                        25, 3),
        ('Temp',                            'aoakenfull7@soundcloud.com',       'blogs.com',            'Cheilanthes bonariensis (Willd.) Proctor',                                                     25, 3),
        ('Tresom',                          'rchipperfield8@yelp.com',          'hhs.gov',              'Carex canescens L. ssp. canescens',                                                            25, 4),
        ('Voltsillam',                      'cconnors9@ca.gov',                 'marriott.com',         'Luzula glabrata (Hoppe ex Rostk.) Desv. var. hitchcockii (Hämet-Ahti) Dorn',                   25, 3),
        ('Voltsillam',                      'cmckniely0@yellowpages.com',       'miitbeian.gov.cn',     'Astragalus grayi Parry ex S. Watson',                                                          25, 5),
        ('Rank',                            'hwillars1@state.gov',              'microsoft.com',        'Calystegia spithamaea (L.) Pursh',                                                             25, 5),
        ('Viva',                            'eplet2@miibeian.gov.cn',           '4shared.com',          'Lecidea promiscens Nyl.',                                                                      25, 5),
        ('Matsoft',                         'lbalffye3@weather.com',            'surveymonkey.com',     'Chenopodium glaucum L.',                                                                       25, 5),
        ('Zontrax',                         'bconaboy4@slashdot.org',           'noaa.gov',             'Cladonia floridana Vain.',                                                                     25, 5),
        ('Y-Solowarm',                      'csperwell5@google.com.br',         'aol.com',              'Talinum gooddingii P. Wilson',                                                                 25, 5),
        ('Veribet',                         'asalvadori6@ted.com',              'npr.org',              'Hierochloe R. Br.',                                                                            25, 5),
        ('Tempsoft',                        'hghidoni7@skyrock.com',            'digg.com',             'Rhynchospora galeana Naczi, W.M. Knapp & Gerry Moore',                                         25, 5),
        ('Bitchip',                         'esavaage0@hostgator.com',          'who.int',              'Lecanora glabrata (Ach.) Malme',                                                               25, 11),
        ('Aerified',                        'hbedenham1@ustream.tv',            '360.cn',               'Sarracenia ×harperi C.R. Bell',                                                                25, 11),
        ('Zaam-Dox',                        'adressell2@ning.com',              'wordpress.org',        'Potentilla ovina Macoun ex J.M. Macoun var. decurrens (S. Watson) S.L. Welsh & B.C. Johnst.',  25, 11),
        ('Mat Lam Tam',                     'kdalling3@usnews.com',             'blog.com',             'Helianthemum carolinianum (Walter) Michx.',                                                    25, 11),
        ('Treeflex',                        'fdinesen4@bandcamp.com',           'constantcontact.com',  'Helianthus angustifolius L.',                                                                  25, 11),
        ('Tresom',                          'bjeannon5@symantec.com',           'nature.com',           'Luzula DC.',                                                                                   25, 11),
        ('Biodex',                          'ssilverman6@a8.net',               'naver.com',            'Trichosalpinx Luer',                                                                           25, 11),
        ('Prodder',                         'vkillford7@un.org',                'example.com',          'Lesquerella ovalifolia Rydb. ex Britton ssp. ovalifolia',                                      25, 11),
        ('Stringtough',                     'slawn8@opera.com',                 'usatoday.com',         'Roccellina franciscana (Zahlbr. ex Herre) Follmann',                                           25, 11),
        ('Voltsillam',                      'ralberti9@bravesites.com',         'netlog.com',           'Cardamine longii Fernald',                                                                     25, 11),
        ('Fix San',                         'tdoniso0@oracle.com',              'fc2.com',              'Xanthoparmelia neowyomingica Hale',                                                            25, 8),
        ('Alphazap',                        'agimbrett1@yolasite.com',          'fda.gov',              'Erigeron speciosus (Lindl.) DC. var. speciosus',                                               25, 7),
        ('Greenlam',                        'emohammed2@jugem.jp',              'geocities.com',        'Trifolium monanthum A. Gray ssp. tenerum (Eastw.) J.M. Gillett',                               25, 7),
        ('Bigtax',                          'fslark3@printfriendly.com',        'multiply.com',         'Astrolepis cochisensis (Goodding) Benham & Windham ssp. arizonica Benham',                     25, 7),
        ('Holdlamis',                       'wblackaller4@fotki.com',           'opensource.org',       'Eritrichium howardii (A. Gray) Rydb.',                                                         25, 7),
        ('Hatity',                          'kmcmichan5@buzzfeed.com',          'examiner.com',         'Allium lemmonii S. Watson',                                                                    25, 7),
        ('Zoolab',                          'hgeratt6@thetimes.co.uk',          'google.pl',            'Horkelia fusca Lindl. ssp. pseudocapitata (Rydb. ex Howell) D.D. Keck',                        25, 8),
        ('Kanlam',                          'cglasper7@cdc.gov',                'amazon.co.jp',         'Grindelia microcephala DC.',                                                                   25, 8),
        ('Regrant',                         'hvedishchev8@telegraph.co.uk',     'merriam-webster.com',  'Barleria prionitis L.',                                                                        25, 7);

INSERT INTO `starrate`(sr_image, sr_hId)
VALUES (1,1),
       (2,1),
       (2,2),
       (5,3);

INSERT INTO `hotelimage`(hi_image_name, hi_hId)
VALUES ('1',1),
       ('3',1),
       ('2',2),
       ('4',3);

INSERT INTO `roomtype`(rt_name, rt_cost, rt_description)
VALUES (N'luxury',        5300000.00, 'TRAVEL'),
       (N'phòng thường',  260000.00,  'RESORT');

INSERT INTO `roomratediscount`(rrd_rate, rrd_startMonth, rrd_endMonth, rrd_rtId)
VALUES (4.00,'2020-04-02 00:00:00','2025-04-02 00:00:00',1),
       (5.00,'2021-02-02 00:00:00','2026-02-02 00:00:00',2);

INSERT INTO `room`(r_number, r_status, r_rtId, r_hId)
VALUES  (1,'DRUM',  2,1),
        (2,'DRUM',  2,1),
        (3,'DRUM',  2,1),
        (5, 'DRUM', 2, 1),
        (6, 'DRUM', 2, 1),
        (7, 'DRUM', 2, 1),
        (8, 'DRUM', 2, 1),
        (9, 'DRUM', 2, 1),
        (10, 'DRUM', 2, 1),
        (11, 'DRUM', 2, 1),
        (12, 'DRUM', 2, 1),
        (13, 'DRUM', 2, 1),
        (14, 'DRUM', 2, 1),
        (15, 'DRUM', 2, 1),
        (16, 'DRUM', 2, 1),
        (17, 'DRUM', 2, 1),
        (18, 'DRUM', 2, 1),
        (19, 'DRUM', 2, 1),
        (20, 'DRUM', 2, 1),
        (21, 'DRUM', 2, 1),
        (22, 'DRUM', 2, 1),
        (23, 'DRUM', 2, 1),
        (24, 'DRUM', 2, 1),
        (25, 'DRUM', 2, 1),
         (1, 'DRUM', 2, 2),
         (2, 'DRUM', 2, 2),
         (3, 'DRUM', 2, 2),
         (4, 'DRUM', 2, 2),
         (5, 'DRUM', 2, 2),
         (6, 'DRUM', 2, 2),
         (7, 'DRUM', 2, 2),
         (8, 'DRUM', 2, 2),
         (9, 'DRUM', 2, 2),
         (10, 'DRUM', 2, 2),
         (11, 'DRUM', 2, 2),
         (12, 'DRUM', 2, 2),
         (13, 'DRUM', 2, 2),
         (14, 'DRUM', 2, 2),
         (15, 'DRUM', 2, 2),
         (16, 'DRUM', 2, 2),
         (17, 'DRUM', 2, 2),
         (18, 'DRUM', 2, 2),
         (19, 'DRUM', 2, 2),
         (20, 'DRUM', 2, 2),
         (1, 'DRUM', 2, 3),
        (2, 'DRUM', 2, 3),
        (3, 'DRUM', 2, 3),
        (4, 'DRUM', 2, 3),
        (5, 'DRUM', 2, 3),
        (6, 'DRUM', 2, 3),
        (7, 'DRUM', 2, 3),
        (8, 'DRUM', 2, 3),
        (9, 'DRUM', 2, 3),
        (10, 'DRUM', 2, 3),
        (11, 'DRUM', 2, 3),
        (12, 'DRUM', 2, 3),
        (13, 'DRUM', 2, 3),
        (14, 'DRUM', 2, 3),
        (15, 'DRUM', 2, 3),
        (16, 'DRUM', 2, 3),
        (17, 'DRUM', 2, 3),
        (18, 'DRUM', 2, 3),
        (19, 'DRUM', 2, 3),
        (20, 'DRUM', 2, 3),
        (1, 'DRUM', 2, 4),
        (2, 'DRUM', 2, 4),
        (3, 'DRUM', 2, 4),
        (4, 'DRUM', 2, 4),
        (5, 'DRUM', 2, 4),
        (6, 'DRUM', 2, 4),
        (7, 'DRUM', 2, 4),
        (8, 'DRUM', 2, 4),
        (9, 'DRUM', 2, 4),
        (10, 'DRUM', 2, 4),
        (11, 'DRUM', 2, 4),
        (12, 'DRUM', 2, 4),
        (13, 'DRUM', 2, 4),
        (14, 'DRUM', 2, 4),
        (15, 'DRUM', 2, 4),
        (16, 'DRUM', 2, 4),
        (17, 'DRUM', 2, 4),
        (18, 'DRUM', 2, 4),
        (19, 'DRUM', 2, 4),
        (20, 'DRUM', 2, 4),
        (1, 'DRUM', 2, 5),
        (2, 'DRUM', 2, 5),
        (3, 'DRUM', 2, 5),
        (4, 'DRUM', 2, 5),
        (5, 'DRUM', 2, 5),
        (6, 'DRUM', 2, 5),
        (7, 'DRUM', 2, 5),
        (8, 'DRUM', 2, 5),
        (9, 'DRUM', 2, 5),
        (10, 'DRUM', 2, 5),
        (11, 'DRUM', 2, 5),
        (12, 'DRUM', 2, 5),
        (13, 'DRUM', 2, 5),
        (14, 'DRUM', 2, 5),
        (15, 'DRUM', 2, 5),
        (16, 'DRUM', 2, 5),
        (17, 'DRUM', 2, 5),
        (18, 'DRUM', 2, 5),
        (19, 'DRUM', 2, 5),
        (20, 'DRUM', 2, 5),
        (1, 'DRUM', 2, 6),
        (2, 'DRUM', 2, 6),
        (3, 'DRUM', 2, 6),
        (4, 'DRUM', 2, 6),
        (5, 'DRUM', 2, 6),
        (6, 'DRUM', 2, 6),
        (7, 'DRUM', 2, 6),
        (8, 'DRUM', 2, 6),
        (9, 'DRUM', 2, 6),
        (10, 'DRUM', 2, 6),
        (11, 'DRUM', 2, 6),
        (12, 'DRUM', 2, 6),
        (13, 'DRUM', 2, 6),
        (14, 'DRUM', 2, 6),
        (15, 'DRUM', 2, 6),
        (16, 'DRUM', 2, 6),
        (17, 'DRUM', 2, 6),
        (18, 'DRUM', 2, 6),
        (19, 'DRUM', 2, 6),
        (20, 'DRUM', 2, 6),
        (1, 'DRUM', 2, 7),
        (2, 'DRUM', 2, 7),
        (3, 'DRUM', 2, 7),
        (4, 'DRUM', 2, 7),
        (5, 'DRUM', 2, 7),
        (6, 'DRUM', 2, 7),
        (7, 'DRUM', 2, 7),
        (8, 'DRUM', 2, 7),
        (9, 'DRUM', 2, 7),
        (10, 'DRUM', 2, 7),
        (11, 'DRUM', 2, 7),
        (12, 'DRUM', 2, 7),
        (13, 'DRUM', 2, 7),
        (14, 'DRUM', 2, 7),
        (15, 'DRUM', 2, 7),
        (16, 'DRUM', 2, 7),
        (17, 'DRUM', 2, 7),
        (18, 'DRUM', 2, 7),
        (19, 'DRUM', 2, 7),
        (20, 'DRUM', 2, 7),
        (1, 'DRUM', 2, 8),
        (2, 'DRUM', 2, 8),
        (3, 'DRUM', 2, 8),
        (4, 'DRUM', 2, 8),
        (5, 'DRUM', 2, 8),
        (6, 'DRUM', 2, 8),
        (7, 'DRUM', 2, 8),
        (8, 'DRUM', 2, 8),
        (9, 'DRUM', 2, 8),
        (10, 'DRUM', 2, 8),
        (11, 'DRUM', 2, 8),
        (12, 'DRUM', 2, 8),
        (13, 'DRUM', 2, 8),
        (14, 'DRUM', 2, 8),
        (15, 'DRUM', 2, 8),
        (16, 'DRUM', 2, 8),
        (17, 'DRUM', 2, 8),
        (18, 'DRUM', 2, 8),
        (19, 'DRUM', 2, 8),
        (20, 'DRUM', 2, 8),
        (1, 'DRUM', 2, 9),
        (2, 'DRUM', 2, 9),
        (3, 'DRUM', 2, 9),
        (4, 'DRUM', 2, 9),
        (5, 'DRUM', 2, 9),
        (6, 'DRUM', 2, 9),
        (7, 'DRUM', 2, 9),
        (8, 'DRUM', 2, 9),
        (9, 'DRUM', 2, 9),
        (10, 'DRUM', 2, 9),
        (11, 'DRUM', 2, 9),
        (12, 'DRUM', 2, 9),
        (13, 'DRUM', 2, 9),
        (14, 'DRUM', 2, 9),
        (15, 'DRUM', 2, 9),
        (16, 'DRUM', 2, 9),
        (17, 'DRUM', 2, 9),
        (18, 'DRUM', 2, 9),
        (19, 'DRUM', 2, 9),
        (20, 'DRUM', 2, 9);
INSERT INTO `booking`(b_date, b_durationOfStay, b_checkInDate, b_checkOutDate, b_typePayment, b_totalRoom, b_hId, b_gId, b_totalAmount, b_status)
VALUES ('2021-04-12 00:00:00',3,'2021-04-12 00:00:00','2021-04-15 00:00:00','BAKING',2,1,2,7200000.00,'PAID'),
       ('2022-04-24 00:00:00',2,'2022-04-24 00:00:00','2022-04-26 00:00:00','DIRECT',3,2,1,6340000.00,'UNPAID');

INSERT INTO `roombook`(rb_rId, rb_bId)
VALUES (1,1),
       (2,2);

INSERT INTO `hotelservices`(hs_name, hs_cost, hs_hId)
VALUES (N'Hoàng Phong',   230000.00,1),
       (N'Hải Đăng',      342700.00,2),
       (N'Hoàng Kiều',    320000.00,3);

INSERT INTO `userservices`
VALUES (1,1),
       (2,2);